# Numpy Assignment

1.    What is a Python library? Why do we use Python libraries?

Ans : Python Library is a collection of functions that by default comes with python compiler. We use python libraries to make developers life easier to by reducing the no. of lines of code and redudancy problems. 


2. What is the difference between Numpy array and List?

Ans : In list, we store heterogeous data in discrete memory locations and collection of those memory references are stored in a list. On the other hand, in numpy array all the homogenous data is stored at one memory location in linear fashion. Just by knowing the first index of an array, we can access all the elements of the array. Same is not true for list. Operations can be done faster in array as compared to list. 

3. Find the shape, size and dimension of the following array?
[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [1]:
import numpy as np

In [2]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr.shape)
print(arr.size)
print(arr.ndim)

(3, 4)
12
2


4. Write python code to access the first row of the following array?
[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [3]:
arr1 = np.array( [[1, 2, 3, 4],[5, 6, 7, 8], [9, 10, 11, 12]])
arr1[0]


array([1, 2, 3, 4])

5. How do you access the element at the third row and fourth column from the given numpy array?
[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [4]:
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr2[2, 3]

12

6. Write code to extract all odd-indexed elements from the given numpy array?
[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [71]:
arr =  np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr[:, 1::2]

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [5]:
arr4 = np.random.randint(0,2, (3,3))

In [6]:
arr4

array([[1, 0, 0],
       [0, 0, 0],
       [1, 1, 1]])

8. Describe the difference between np.random.rand and np.random.randn?

np.random.rand generates numbers from a uniform distribution in the range [0, 1)
and np.random.randn generates numbers from a normal distribution in the range [0,1) with mean of 0 and std of 1

 9. Write code to increase the dimension of the following array?[[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]

In [13]:
# Solution 1
arr5 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
np.expand_dims(arr5, axis = 0)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [14]:
# Solution 2
np.reshape(arr5, (2,2,3))

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

10. How to transpose the following array in NumPy?
[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [15]:
arr6 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr6.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

11. Consider the following matrix:
Matrix A2 [[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B2 [[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]]

In [20]:
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
B = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])



In [17]:
# index wise multiplication

In [21]:
A * B

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [22]:
#  Matix multiplication

In [24]:
A @ B     # not possible as A has shape(3,4) and B has shape(3,4)   

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [25]:
# Add both the matices

In [26]:
A + B

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [27]:
# Subtact matix B from A

In [28]:
A - B

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [29]:
# Divide Matix B by A

In [30]:
B / A

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

12. Which function in Numpy can be used to swap the byte order of an array?

ndarray.byteswap()

13. What is the significance of the np.linalg.inv function?

The np.linalg.inv function in Python's NumPy library is used to calculate the inverse of a matrix.

In [54]:
# if we multiply A and it's inverse, result will be an identity matrix only if inverse matrix exists
arr = np.array([[1, 2, 3], [5, 6, 3],[9, 10, 11]])
inv = np.linalg.inv(arr)
print(inv)

[[-1.125 -0.25   0.375]
 [ 0.875  0.5   -0.375]
 [ 0.125 -0.25   0.125]]


14. What does the np.reshape function do, and how is it used?

It is used to change the shape of the array without altering the size of the array

In [57]:
# example
a = np.array( [[4,3,32,3],[32,4,2,3]])
print(a.shape)
print(a.size)

(2, 4)
8


In [63]:
a = a.reshape((2,2,2))
print(a.shape)
print(a.size)

(2, 2, 2)
8


15. What is broadcasting in Numpy?

broadcasting refers to the ability to perform arithmetic operations on arrays of different shapes by aligning their dimensions

In [65]:
# example
b = np.zeros((3,3))
b


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [66]:
b + 5

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])